model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
checkpoint:
    filepath: './test_checkpoints'
    monitor_val: 'abs_rel'
    monitor_train: 'single_step-loss'
    period: 0
    save_freq_in_train: 1000 
datasets:
    augmentation:
        image_shape: (544, 960)
    train:
        batch_size: 1
        dataset: ['Image']
        #path: ['/home/kopernikus/Downloads/moving_actors_ds']
        path: ['/HDD/Documents/Google Drive/Archivos_compartidos/Kopernikus_General/Training_videos/ML_videos/moving_actors/moving_actors_ds']
        split: ['{:d}']
        depth_type: ['']
        repeat: [1]
        num_workers: 48
        num_logs: 1000
    validation:
        dataset: ['KITTI']
        path: ['data/datasets/KITTI_tiny']
        split: ['kitti_tiny.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['data/datasets/KITTI_tiny']
        split: ['kitti_tiny.txt']
        depth_type: ['velodyne']
wandb:
    dry_run: False                                # Wandb dry-run (not logging)
    name: 'Test_packnet'                          # Wandb run name
    project: os.environ.get("WANDB_PROJECT", "")  # Wandb project
    entity: os.environ.get("WANDB_ENTITY", "")    # Wandb entity
    tags: []                                      # Wandb tags
    dir: './logs'    
